# Lab 02 - Extração de Dados: Arquivos Planos
**Disciplina:** Extração e Preparação de Dados | **Professor:** Luis Aramis

Neste laboratório, vamos praticar a leitura de diferentes formatos de arquivos planos (CSV, Excel) e lidar com problemas comuns como codificação, delimitadores e metadados.

## 1. Setup
Importe a biblioteca pandas.

In [1]:
import pandas as pd

## 2. CSV Padrão
Carregue o arquivo `vendas.csv` e exiba as 5 primeiras linhas.

In [3]:
df = pd.read_csv ("vendas.csv")
print(df)

    id_venda        data   produto  quantidade  preco_unitario     total
0          1  2024-01-01   Teclado           1         2852.92   2852.92
1          2  2024-01-02   Teclado           7         3249.47  22746.29
2          3  2024-01-03   Teclado           7         4104.96  28734.72
3          4  2024-01-04   Teclado           1          870.74    870.74
4          5  2024-01-05  Notebook           7         3614.27  25299.89
5          6  2024-01-06  Notebook           4         2646.89  10587.56
6          7  2024-01-07  Notebook           2         4519.01   9038.02
7          8  2024-01-08  Notebook           7          915.07   6405.49
8          9  2024-01-09   Monitor           3         1220.41   3661.23
9         10  2024-01-10  Notebook           9         3994.96  35954.64
10        11  2024-01-11     Mouse           6         3646.87  21881.22
11        12  2024-01-12   Teclado           5         3794.34  18971.70
12        13  2024-01-13   Monitor           8         4586.16  36689.28
13        14  2024-01-14     Mouse           3         4376.23  13128.69
14        15  2024-01-15   Teclado           3          803.17   2409.51
15        16  2024-01-16   Teclado           6         2674.20  16045.20
16        17  2024-01-17   Monitor           1         4544.62   4544.62
17        18  2024-01-18  Notebook           5          410.34   2051.70
18        19  2024-01-19   Monitor           3         3432.17  10296.51
19        20  2024-01-20  Notebook           5         3065.50  15327.50

## 3. CSV com Problemas (Delimitador e Encoding)
Tente carregar o arquivo `produtos_brasil.csv`.
Você encontrará erros. Corrija utilizando os parâmetros `sep` e `encoding`.
Obs: O separador é `;` e o encoding é `latin1`.

In [4]:
import pandas as pd

df = pd.read_csv(
    "produtos_brasil.csv",
    sep=";",       
    encoding="latin1" 
)

df.head()

    id           nome preco_reais
0  101           Café       32,75
1  102         Feijão       49,96
2  103  Pão de Queijo       32,98
3  104           Açaí        6,24
4  105        Guaraná       19,24

## 4. Excel com Múltiplas Abas
Carregue a aba 'Jan' do arquivo `relatorio_financeiro.xlsx`.
Observe que o cabeçalho não está na primeira linha. Use o parâmetro `header` ou `skiprows` para corrigir.

In [21]:
df = pd.read_excel(
    "relatorio_financeiro.xlsx",
    sheet_name="Jan",
    header=2
)

df.head()

  Unnamed: 0 Unnamed: 1
0        Dia    Receita
1          1       4475
2          2       2561
3          3       4247
4          4       3347

## 5. Delimitadores Exóticos
Carregue o arquivo `movies.csv`. Ele usa o caractere `|` como separador.

In [8]:
df = pd.read_csv(
    "movies.csv",
    sep="|"
)

df.head()

   movie_id         title  year
0         1     Inception  2010
1         2    The Matrix  1999
2         3  Interstellar  2014
3         4      Parasite  2019
4         5      Avengers  2012

## 6. Arquivos com Metadados no Início
O arquivo `ibge_metadata.csv` possui 3 linhas de texto antes do cabeçalho real.
Use o parâmetro `skiprows` para ignorá-las. Dica: encoding `cp1252`.

In [10]:
df = pd.read_csv(
    "ibge_metadata.csv",
    skiprows=3,    
    encoding="cp1252" 
)   

print(df.head())

   cod_municipio  nome_municipio  populacao_estimada
0        3550308       São Paulo            11451245
1        3304557  Rio de Janeiro             6211423
2        3106200  Belo Horizonte             2438423

---
## PARTE 2: APROFUNDAMENTO
Tratamento de Arquivos Massivos e Múltiplos Arquivos.

## 7. Leitura em Chunks (Big Files)
O arquivo `big_file.csv` simula um arquivo grande. Leia-o em pedaços (chunks) de 10.000 linhas e exiba o tipo do objeto resultante.

In [11]:
chunk_iter = pd.read_csv("big_file.csv", chunksize=10000)
for chunk in chunk_iter:
    print(f'chunk shape: [chunk.shape]')
    break

chunk shape: [chunk.shape]

## 8. Linhas com Erro (Bad Lines)
O arquivo `bad_lines.csv` possui linhas quebradas. Tente carregar ignorando as linhas com erro utilizando `on_bad_lines`.

In [12]:
df_bad = pd.read_csv('bad_lines.csv', on_bad_lines='skip')
df.head()

   cod_municipio  nome_municipio  populacao_estimada
0        3550308       São Paulo            11451245
1        3304557  Rio de Janeiro             6211423
2        3106200  Belo Horizonte             2438423

## 9. Múltiplos Arquivos (Glob)
Use a biblioteca `glob` para listar os arquivos na pasta `batch_data/` e carregá-los em um único DataFrame com `pd.concat`.

In [13]:
import glob
arquivos = glob.glob('batch_data/*.csv')
dfs = [pd.read_csv(arquivos) for arquivos in arquivos]
df_final = pd.concat(dfs, ignore_index=True)

df_final.head()
df_final.shape

(30, 2)

---
## PARTE 3: NÍVEL EXPERT
Otimização e Limpeza Avançada.

## 10. Otimização de Memória (Downcasting)
1. Carregue o arquivo `big_file.csv` inteiro (se couber) ou um chunk.
2. Verifique o uso de memória com `.info(memory_usage='deep')`.
3. Converta uma coluna numérica para `float32` ou `int32` e verifique a réduction do uso de memória.

In [20]:
df = pd.read_csv("big_file.csv")
df.head()
df.info(memory_usage='deep')
#df.dtypes

df = df.astype({
    "A": "int32",
    "B": "int32",
    "C": "int32",
    "D": "int32",
    "E": "int32"
})
df.info(memory_usage='deep')

df = df.astype({
    "A": "int64",
    "B": "int64",
    "C": "int64",
    "D": "int64",
    "E": "int64"
})

df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       50000 non-null  int64
 1   B       50000 non-null  int64
 2   C       50000 non-null  int64
 3   D       50000 non-null  int64
 4   E       50000 non-null  int64
dtypes: int64(5)
memory usage: 1.9 MB
<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       50000 non-null  int32
 1   B       50000 non-null  int32
 2   C       50000 non-null  int32
 3   D       50000 non-null  int32
 4   E       50000 non-null  int32
dtypes: int32(5)
memory usage: 976.7 KB
<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       50000 non-null  int64
 1   B       50000 non-null  int64
 2   C       50000 non-null  int64
 3   D       50000 non-null  int64
 4   E       50000 non-null  int64
dtypes: int64(5)
memory usage: 1.9 MB

## 11. Extração com Regex
Suponha a seguinte coluna de texto sujo. Crie um DataFrame com ela e use `str.extract` para obter apenas o código numérico.
```python
dados = {'Info': ['Produto: [123] - Vendido', 'Produto: [456] - Estoque', 'Produto: [789] - Devolvido']}
```

In [17]:
import pandas as pd 
dados = {'Info': ['Produto: [123] - Vendido', 'Produto: [456] - Estoque', 'Produto: [789] - Devolvido']}
print(dados)
df = pd.DataFrame(dados)
df["codigo"]= df["Info"].str.extract(r"\[(\d+)\]")
print(df)
print(df["codigo"])

{'Info': ['Produto: [123] - Vendido', 'Produto: [456] - Estoque', 'Produto: [789] - Devolvido']}
                         Info codigo
0    Produto: [123] - Vendido    123
1    Produto: [456] - Estoque    456
2  Produto: [789] - Devolvido    789
0    123
1    456
2    789
Name: codigo, dtype: str

---
## 12. DESAFIO PARA CASA (Real Data)
1. Entre no site [dados.gov.br](https://dados.gov.br) ou [Kaggle](https://kaggle.com).
2. Baixe um dataset CSV de seu interesse (tamanho mínimo: 1000 linhas).
3. Carregue-o no pandas, tratando problemas de encoding/separador se houver.
4. Exiba um `.info()` e `.describe()`.
5. Responda: Qual o tamanho do arquivo em memória?

In [19]:
import pandas as pd 
df = pd.read_csv('ultimate_student_productivity_dataset_5000.csv', sep=",")
df.head()
df.info
df.describe
df.info(memory_usage='deep')

#memory usage: 1.5 MB

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            5000 non-null   int64
 1   age                   5000 non-null   int64
 2   gender                5000 non-null   str
 3   academic_level        5000 non-null   str
 4   study_hours           5000 non-null   float64
 5   self_study_hours      5000 non-null   float64
 6   online_classes_hours  5000 non-null   float64
 7   social_media_hours    5000 non-null   float64
 8   gaming_hours          5000 non-null   float64
 9   sleep_hours           5000 non-null   float64
 10  screen_time_hours     5000 non-null   float64
 11  exercise_minutes      5000 non-null   int64
 12  caffeine_intake_mg    5000 non-null   int64
 13  part_time_job         5000 non-null   int64
 14  upcoming_deadline     5000 non-null   int64
 15  internet_quality      5000 non-null   str
 16  mental_health_score   5000 non-null   int64
 17  focus_index           5000 non-null   float64
 18  burnout_level         5000 non-null   float64
 19  productivity_score    5000 non-null   float64
 20  exam_score            5000 non-null   float64
dtypes: float64(11), int64(7), str(3)
memory usage: 1.5 MB